name: CI Fedora 44

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:44
      options: --security-opt seccomp=unconfined
    steps:
      - name: Cache dnf packages
        uses: actions/cache@v4
        with:
          path: /var/cache/dnf
          key: dnf-fedora44-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            dnf-fedora44-
      - name: Setup git
        run: |
          id
          ls -la
          dnf -y install git
      - uses: actions/checkout@v6
        with:
          path: "libadwaitamm-src"
      - name: Setup dependencies
        run: |
          ls -la libadwaitamm-src
          adduser -m -U -d /home/user  user
          mv libadwaitamm-src /home/user
          chown -R user:user /home/user/libadwaitamm-src
          dnf -y install gcc-c++ gtkmm4.0-devel meson itstool libadwaita-devel mm-common weston glibc-langpack-en
      - name: Configure
        working-directory: /home/user/libadwaitamm-src
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: |
          sudo -u user -E -- meson setup builddir
      - name: Build
        working-directory: /home/user/libadwaitamm-src/builddir
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: |
          sudo -u user -E -- meson compile
      - name: Test
        working-directory: /home/user/libadwaitamm-src/builddir
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          GSK_RENDERER: cairo
          LIBGL_ALWAYS_SOFTWARE: "1"
        run: |
          sudo -u user -E --  /home/user/libadwaitamm-src/.github/scripts/run-tests.sh
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: testlog.txt
          path: /home/user/libadwaitamm-src/builddir/meson-logs/testlog.txt
      - name: Dist
        working-directory: /home/user/libadwaitamm-src/builddir
        run: |
          sudo -u user -- git status
          sudo -u user -- meson dist --no-tests
